spring:
  jpa:
    properties:
      hibernate.default_schema: warehouse
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse
    username: postgres
    password: postgres

app:
  notifications:
    email:
      isChannelEnabled: true
      name: "email"
    sms:
      isChannelEnabled: true
      name: "sms"
